#!/bin/bash

MAKEBASEAPP=`which makeBaseApp 2> /dev/null`
if [ $? -ne 0 ] ; then
  MAKEBASEAPP=`which makeBaseApp.pl 2> /dev/null`
  if [ $? -ne 0 ] ; then
    >&2 echo "ERROR: Cannot find makeBaseApp executable!"
    exit 1;
  fi
fi

## configure isegioc
TOP=${PWD}/../tmp/isegioc
ORIG=${PWD}
LIB_NAME=devisegHAL
SYS_LIBS="isegHAL-client"

mkdir -p $TOP
(cd $TOP; $MAKEBASEAPP -t support ${LIB_NAME})

## Add source files for isegHAL support
LIB_SRC=`find ${ORIG}/src/ -name "*.c*" -exec basename "{}" \; | xargs echo`
LIB_DBD=`find ${ORIG}/src/ -name "*.dbd" -exec basename "{}" \; | xargs echo`
cp -a ${ORIG}/src ${TOP}/${LIB_NAME}App/.
sed -i \
		-e "/^#${LIB_NAME}_SRCS += xxx/a ${LIB_NAME}_SRCS += $LIB_SRC" \
		-e "s/^DBD += ${LIB_NAME}.dbd/DBD += $LIB_DBD/" \
		-e "/^${LIB_NAME}_LIBS +=.*/a ${LIB_NAME}_SYS_LIBS += $SYS_LIBS" \
		${TOP}/${LIB_NAME}App/src/Makefile


